module.exports.descriptors = [
  "Himalayan",
  "Nilgiri",
  "Western Ghats",
  "Eastern Ghats",
  "Coastal",
  "Backwater",
  "Riverfront",
  "Lakeside",
  "Hilltop",
  "Valley",
  "Forest",
  "Jungle",
  "Bamboo",
  "Coconut Grove",
  "Tea Estate",
  "Coffee Estate",
  "Spice Garden",
  "Sunrise",
  "Sunset",
  "Monsoon",
  "Sacred",
  "Heritage",
  "Royal",
  "Desert",
  "Cold Desert",
  "Tribal",
  "Green",
  "Misty",
  "Wild",
  "Serene",
  "Golden Sands",
  "Ocean View",
  "Rainforest",
  "Waterfall",
  "Hidden",
  "Adventure"
];

module.exports.places = [
  "Camp",
  "Campsite",
  "Nature Camp",
  "Eco Camp",
  "Forest Camp",
  "Hill Camp",
  "River Camp",
  "Beach Camp",
  "Valley Camp",
  "Tent Stay",
  "Homestay",
  "Retreat",
  "Resort Camp",
  "Hut Stay",
  "Treehouse Stay",
  "Lake View Stay",
  "River View Stay",
  "Backwater Stay",
  "View Point",
  "Safari Camp",
  "Wildlife Camp",
  "Tea Bungalow",
  "Estate Stay",
  "Cottage Stay",
  "Jungle Lodge",
  "Nature Lodge",
  "Traveller's Nest",
  "Adventure Base",
  "Camping Grounds",
  "Picnic Spot"
];
